name: gymapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <3.1.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.17.0
  flutter_heatmap_calendar: ^1.0.5
  table_calendar: ^3.0.5
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.3.9
  fl_chart: ^0.55.2
  uuid: ^3.0.7
  flutter_native_splash: ^2.2.19
  http: ^0.13.6
  excel: ^2.0.1
  path_provider: ^2.0.11
  url_launcher: ^6.1.5
  collection: ^1.17.0
  pie_chart: ^5.1.0
  material_design_icons_flutter: ^6.0.7096
  barcode_scan2: ^4.2.0
  firebase_core: ^2.4.1
  cloud_firestore: ^4.3.1
  firebase_auth: ^4.2.5
  google_sign_in: ^5.4.2
  syncfusion_flutter_charts: ^20.4.54
  cloud_functions: ^4.3.1
  crypto: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/overloadlogo.png"
  adaptive_icon_background: "#000000"    # or your brand color (e.g., "#1e1e1e")
  adaptive_icon_foreground: "lib/assets/overloadlogo.png"
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  hive_generator: ^1.1.3
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/
    - lib/assets/overloadblacklogo.png
