import 'package:hive/hive.dart';

part 'step_log.g.dart'; // This file will be generated by Hive generator

@HiveType(typeId: 2) // Ensure typeId is unique if you have other Hive objects
class StepLog {
  @HiveField(0)
  final DateTime date;

  @HiveField(1)
  final int steps;

  StepLog({
    required this.date,
    required this.steps,
  });
}
