import 'package:hive/hive.dart';

part 'weight_log.g.dart'; // This file is generated by Hive generator

@HiveType(typeId: 1) // Unique typeId for each HiveType
class WeightLog {
  @HiveField(0)
  final DateTime date;

  @HiveField(1)
  final double weight;

  WeightLog({required this.date, required this.weight});
}
