// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_JQeM5PzMDIG8pvwY9fPL_beApfoThyE',
    appId: '1:644555737003:web:4c7f00852d3b3fcb84b4ee',
    messagingSenderId: '644555737003',
    projectId: 'gymapp-2d58a',
    authDomain: 'gymapp-2d58a.firebaseapp.com',
    storageBucket: 'gymapp-2d58a.firebasestorage.app',
    measurementId: 'G-RZLDVYP65L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBswSBU2h7S9q6xXRV3t5jDNLHDahXMhco',
    appId: '1:644555737003:android:29fc86ae335dec4d84b4ee',
    messagingSenderId: '644555737003',
    projectId: 'gymapp-2d58a',
    storageBucket: 'gymapp-2d58a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBri8QQASg3ciyTKq2zVIbPMIr7vh-aX2U',
    appId: '1:644555737003:ios:b7b3463a99cebebe84b4ee',
    messagingSenderId: '644555737003',
    projectId: 'gymapp-2d58a',
    storageBucket: 'gymapp-2d58a.firebasestorage.app',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBri8QQASg3ciyTKq2zVIbPMIr7vh-aX2U',
    appId: '1:644555737003:ios:b7b3463a99cebebe84b4ee',
    messagingSenderId: '644555737003',
    projectId: 'gymapp-2d58a',
    storageBucket: 'gymapp-2d58a.firebasestorage.app',
    iosBundleId: 'com.example.gymapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_JQeM5PzMDIG8pvwY9fPL_beApfoThyE',
    appId: '1:644555737003:web:c8d3811f92f3580084b4ee',
    messagingSenderId: '644555737003',
    projectId: 'gymapp-2d58a',
    authDomain: 'gymapp-2d58a.firebaseapp.com',
    storageBucket: 'gymapp-2d58a.firebasestorage.app',
    measurementId: 'G-3R7FLYQV8V',
  );
}
